code --install-extension DavidAnson.vscode-markdownlint
code --install-extension DavidWang.ini-for-vscode
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-material-theme
code --install-extension formulahendry.auto-close-tag
code --install-extension humao.rest-client
code --install-extension jpogran.puppet-vscode
code --install-extension kraftwer1.darcula-extra
code --install-extension lamartire.git-indicators
code --install-extension mauve.terraform
code --install-extension mhutchie.git-graph
code --install-extension mrmlnc.vscode-apache
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension raynigon.nginx-formatter
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-openshift-connector
code --install-extension redhat.vscode-yaml
code --install-extension rokoroku.vscode-theme-darcula
code --install-extension shanoor.vscode-nginx
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sldobri.darcula-5-stars
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscoss.vscode-ansible
code --install-extension wayou.vscode-todo-highlight
code --install-extension yzhang.markdown-all-in-one
